---

name: build-check
on: [push, pull_request]
jobs:
  build-check:
    name: Go Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.17'
          - '1.16'
          - '1.15'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make build_check
  test-coverage:
    name: Go Test With Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Get test coverage
        run: make tests
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
